// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ServiceStatus {
    "id": string;
    "label": string;
    "description": string;
    "port": number;
    "state": State;
    "unit": string;

    /** Creates a new ServiceStatus instance. */
    constructor($$source: Partial<ServiceStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceStatus($$parsedSource as Partial<ServiceStatus>);
    }
}

export class Snapshot {
    "generatedAt": string;
    "platform": string;
    "supported": boolean;
    "services": ServiceStatus[];
    "warnings": string[];
    "lastError": string;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("services" in $$source)) {
            this["services"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField3_0($$parsedSource["services"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateRunning = "running",
    StateStopped = "stopped",
    StateUnavailable = "unavailable",
};

// Private type creation functions
const $$createType0 = ServiceStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
