// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

export class CommandMeta {
    "name": string;
    "args"?: string[];
    "cwd"?: string;

    /** Creates a new CommandMeta instance. */
    constructor($$source: Partial<CommandMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandMeta {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        return new CommandMeta($$parsedSource as Partial<CommandMeta>);
    }
}

export class Event {
    "schemaVersion": number;
    "id": string;
    "timestamp": string;
    "sourceType": string;
    "projectRoot": string;
    "phpSapi": string;
    "requestId": string | null;
    "http"?: HTTPMeta | null;
    "command"?: CommandMeta | null;
    "isDd": boolean;
    "payloadFormat": string;
    "payload": json$0.RawMessage;
    "trace": TraceFrame[];
    "host": HostMeta;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = "";
        }
        if (!("projectRoot" in $$source)) {
            this["projectRoot"] = "";
        }
        if (!("phpSapi" in $$source)) {
            this["phpSapi"] = "";
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = null;
        }
        if (!("isDd" in $$source)) {
            this["isDd"] = false;
        }
        if (!("payloadFormat" in $$source)) {
            this["payloadFormat"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = null;
        }
        if (!("trace" in $$source)) {
            this["trace"] = [];
        }
        if (!("host" in $$source)) {
            this["host"] = (new HostMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        const $$createField12_0 = $$createType6;
        const $$createField13_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("http" in $$parsedSource) {
            $$parsedSource["http"] = $$createField7_0($$parsedSource["http"]);
        }
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField8_0($$parsedSource["command"]);
        }
        if ("trace" in $$parsedSource) {
            $$parsedSource["trace"] = $$createField12_0($$parsedSource["trace"]);
        }
        if ("host" in $$parsedSource) {
            $$parsedSource["host"] = $$createField13_0($$parsedSource["host"]);
        }
        return new Event($$parsedSource as Partial<Event>);
    }
}

export class HTTPMeta {
    "method": string;
    "scheme": string;
    "host": string;
    "path": string;
    "query"?: string;
    "statusCode"?: number | null;
    "clientIp"?: string;
    "userAgent"?: string;

    /** Creates a new HTTPMeta instance. */
    constructor($$source: Partial<HTTPMeta> = {}) {
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPMeta($$parsedSource as Partial<HTTPMeta>);
    }
}

export class HostMeta {
    "hostname": string;
    "pid": number;

    /** Creates a new HostMeta instance. */
    constructor($$source: Partial<HostMeta> = {}) {
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): HostMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostMeta($$parsedSource as Partial<HostMeta>);
    }
}

export class TraceFrame {
    "file"?: string;
    "line"?: number;
    "func"?: string;

    /** Creates a new TraceFrame instance. */
    constructor($$source: Partial<TraceFrame> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraceFrame instance from a string or object.
     */
    static createFrom($$source: any = {}): TraceFrame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraceFrame($$parsedSource as Partial<TraceFrame>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = HTTPMeta.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = CommandMeta.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = TraceFrame.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = HostMeta.createFrom;
