// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActionResult {
    "success": boolean;
    "supported": boolean;
    "version": string;
    "command": string;
    "requiresPrivilege": boolean;
    "suggestedCommands": string[];
    "message": string;
    "error": string;

    /** Creates a new ActionResult instance. */
    constructor($$source: Partial<ActionResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("requiresPrivilege" in $$source)) {
            this["requiresPrivilege"] = false;
        }
        if (!("suggestedCommands" in $$source)) {
            this["suggestedCommands"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionResult {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("suggestedCommands" in $$parsedSource) {
            $$parsedSource["suggestedCommands"] = $$createField5_0($$parsedSource["suggestedCommands"]);
        }
        return new ActionResult($$parsedSource as Partial<ActionResult>);
    }
}

export class Extension {
    "name": string;
    "enabled": boolean;
    "scope": string;
    "iniPath": string;
    "iniExists": boolean;

    /** Creates a new Extension instance. */
    constructor($$source: Partial<Extension> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("iniPath" in $$source)) {
            this["iniPath"] = "";
        }
        if (!("iniExists" in $$source)) {
            this["iniExists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extension instance from a string or object.
     */
    static createFrom($$source: any = {}): Extension {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Extension($$parsedSource as Partial<Extension>);
    }
}

export class ExtensionToggleRequest {
    "name": string;
    "enabled": boolean;

    /** Creates a new ExtensionToggleRequest instance. */
    constructor($$source: Partial<ExtensionToggleRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionToggleRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionToggleRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtensionToggleRequest($$parsedSource as Partial<ExtensionToggleRequest>);
    }
}

export class IniSettings {
    "uploadMaxFilesize": string;
    "postMaxSize": string;
    "memoryLimit": string;
    "maxExecutionTime": string;

    /** Creates a new IniSettings instance. */
    constructor($$source: Partial<IniSettings> = {}) {
        if (!("uploadMaxFilesize" in $$source)) {
            this["uploadMaxFilesize"] = "";
        }
        if (!("postMaxSize" in $$source)) {
            this["postMaxSize"] = "";
        }
        if (!("memoryLimit" in $$source)) {
            this["memoryLimit"] = "";
        }
        if (!("maxExecutionTime" in $$source)) {
            this["maxExecutionTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IniSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): IniSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IniSettings($$parsedSource as Partial<IniSettings>);
    }
}

export class IniSettingsUpdateRequest {
    "uploadMaxFilesize": string;
    "postMaxSize": string;
    "memoryLimit": string;
    "maxExecutionTime": string;

    /** Creates a new IniSettingsUpdateRequest instance. */
    constructor($$source: Partial<IniSettingsUpdateRequest> = {}) {
        if (!("uploadMaxFilesize" in $$source)) {
            this["uploadMaxFilesize"] = "";
        }
        if (!("postMaxSize" in $$source)) {
            this["postMaxSize"] = "";
        }
        if (!("memoryLimit" in $$source)) {
            this["memoryLimit"] = "";
        }
        if (!("maxExecutionTime" in $$source)) {
            this["maxExecutionTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IniSettingsUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): IniSettingsUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IniSettingsUpdateRequest($$parsedSource as Partial<IniSettingsUpdateRequest>);
    }
}

export class Snapshot {
    "generatedAt": string;
    "supported": boolean;
    "platform": string;
    "activeVersion": string;
    "versions": Version[];
    "settings": IniSettings;
    "extensions": Extension[];
    "warnings": string[];
    "lastError": string;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("activeVersion" in $$source)) {
            this["activeVersion"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new IniSettings());
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField4_0($$parsedSource["versions"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField5_0($$parsedSource["settings"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField6_0($$parsedSource["extensions"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class Version {
    "version": string;
    "installed": boolean;
    "active": boolean;

    /** Creates a new Version instance. */
    constructor($$source: Partial<Version> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     */
    static createFrom($$source: any = {}): Version {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Version($$parsedSource as Partial<Version>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Version.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = IniSettings.createFrom;
const $$createType4 = Extension.createFrom;
const $$createType5 = $Create.Array($$createType4);
