// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dump$0 from "../dump/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DecodeDumpEventNDJSONLine(line: string): $CancellablePromise<dump$0.Event | null> {
    return $Call.ByID(2282382060, line).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DumpEventChannelName(): $CancellablePromise<string> {
    return $Call.ByID(2064947480);
}

export function GetCollectorStatus(): $CancellablePromise<$models.CollectorStatus> {
    return $Call.ByID(678154095).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetRecentEvents(limit: number): $CancellablePromise<dump$0.Event[]> {
    return $Call.ByID(599144652, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SupportedDumpEventSchemaVersion(): $CancellablePromise<number> {
    return $Call.ByID(392301343);
}

// Private type creation functions
const $$createType0 = dump$0.Event.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CollectorStatus.createFrom;
const $$createType3 = $Create.Array($$createType0);
