// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CollectorStatus {
    "running": boolean;
    "socketPath": string;
    "lastError": string;
    "dropped": number;

    /** Creates a new CollectorStatus instance. */
    constructor($$source: Partial<CollectorStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("socketPath" in $$source)) {
            this["socketPath"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CollectorStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CollectorStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CollectorStatus($$parsedSource as Partial<CollectorStatus>);
    }
}
