// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as phpmanager$0 from "../domain/phpmanager/models.js";

export function GetPHPManagerSnapshot(): $CancellablePromise<phpmanager$0.Snapshot> {
    return $Call.ByID(498487661).then(($result: any) => {
        return $$createType0($result);
    });
}

export function InstallPHPVersion(version: string): $CancellablePromise<phpmanager$0.ActionResult> {
    return $Call.ByID(687587217, version).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetPHPExtensionState(request: phpmanager$0.ExtensionToggleRequest): $CancellablePromise<phpmanager$0.ActionResult> {
    return $Call.ByID(2213040700, request).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SwitchPHPVersion(version: string): $CancellablePromise<phpmanager$0.ActionResult> {
    return $Call.ByID(586753686, version).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdatePHPIniSettings(request: phpmanager$0.IniSettingsUpdateRequest): $CancellablePromise<phpmanager$0.ActionResult> {
    return $Call.ByID(254775976, request).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = phpmanager$0.Snapshot.createFrom;
const $$createType1 = phpmanager$0.ActionResult.createFrom;
