// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as servicesstatus$0 from "../domain/servicesstatus/models.js";

export function GetServicesStatus(): $CancellablePromise<servicesstatus$0.Snapshot> {
    return $Call.ByID(782139552).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = servicesstatus$0.Snapshot.createFrom;
