// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as setup$0 from "../setup/models.js";

export function ApplyValetLinuxRemediation(confirm: boolean): $CancellablePromise<setup$0.ValetLinuxRemediationResult> {
    return $Call.ByID(3981884522, confirm).then(($result: any) => {
        return $$createType0($result);
    });
}

export function EnableCLIHook(): $CancellablePromise<setup$0.HookInstallResult> {
    return $Call.ByID(3486349685).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSetupDiagnostics(): $CancellablePromise<setup$0.Diagnostics> {
    return $Call.ByID(1874792066).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetValetLinuxVerification(): $CancellablePromise<setup$0.ValetLinuxVerification> {
    return $Call.ByID(4123474282).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetValetSites(): $CancellablePromise<setup$0.ValetSitesResult> {
    return $Call.ByID(3284235411).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = setup$0.ValetLinuxRemediationResult.createFrom;
const $$createType1 = setup$0.HookInstallResult.createFrom;
const $$createType2 = setup$0.Diagnostics.createFrom;
const $$createType3 = setup$0.ValetLinuxVerification.createFrom;
const $$createType4 = setup$0.ValetSitesResult.createFrom;
