// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Diagnostics {
    "generatedAt": string;
    "phpFound": boolean;
    "phpVersion": string;
    "phpIniOutput": string;
    "serviceManager": string;
    "lastError": string;

    /** Creates a new Diagnostics instance. */
    constructor($$source: Partial<Diagnostics> = {}) {
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }
        if (!("phpFound" in $$source)) {
            this["phpFound"] = false;
        }
        if (!("phpVersion" in $$source)) {
            this["phpVersion"] = "";
        }
        if (!("phpIniOutput" in $$source)) {
            this["phpIniOutput"] = "";
        }
        if (!("serviceManager" in $$source)) {
            this["serviceManager"] = "";
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): Diagnostics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagnostics($$parsedSource as Partial<Diagnostics>);
    }
}

export class FPMServiceStatus {
    "serviceName": string;
    "version": string;
    "confDPath": string;
    "hookIniPath": string;
    "hookIniExists": boolean;
    "autoPrependFile": string;
    "matchesExpected": boolean;
    "systemdActive": boolean;
    "systemdEnabled": boolean;
    "restartCommand": string;
    "verificationCommand": string;

    /** Creates a new FPMServiceStatus instance. */
    constructor($$source: Partial<FPMServiceStatus> = {}) {
        if (!("serviceName" in $$source)) {
            this["serviceName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("confDPath" in $$source)) {
            this["confDPath"] = "";
        }
        if (!("hookIniPath" in $$source)) {
            this["hookIniPath"] = "";
        }
        if (!("hookIniExists" in $$source)) {
            this["hookIniExists"] = false;
        }
        if (!("autoPrependFile" in $$source)) {
            this["autoPrependFile"] = "";
        }
        if (!("matchesExpected" in $$source)) {
            this["matchesExpected"] = false;
        }
        if (!("systemdActive" in $$source)) {
            this["systemdActive"] = false;
        }
        if (!("systemdEnabled" in $$source)) {
            this["systemdEnabled"] = false;
        }
        if (!("restartCommand" in $$source)) {
            this["restartCommand"] = "";
        }
        if (!("verificationCommand" in $$source)) {
            this["verificationCommand"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FPMServiceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): FPMServiceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FPMServiceStatus($$parsedSource as Partial<FPMServiceStatus>);
    }
}

export class HookInstallResult {
    "success": boolean;
    "alreadyEnabled": boolean;
    "phpIniPath": string;
    "prependPath": string;
    "backupPath": string;
    "socketPath": string;
    "requiresSudo": boolean;
    "suggestedCmd": string;
    "privilegeStrategy": string;
    "privilegeAttempted": boolean;
    "message": string;
    "error": string;

    /** Creates a new HookInstallResult instance. */
    constructor($$source: Partial<HookInstallResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("alreadyEnabled" in $$source)) {
            this["alreadyEnabled"] = false;
        }
        if (!("phpIniPath" in $$source)) {
            this["phpIniPath"] = "";
        }
        if (!("prependPath" in $$source)) {
            this["prependPath"] = "";
        }
        if (!("backupPath" in $$source)) {
            this["backupPath"] = "";
        }
        if (!("socketPath" in $$source)) {
            this["socketPath"] = "";
        }
        if (!("requiresSudo" in $$source)) {
            this["requiresSudo"] = false;
        }
        if (!("suggestedCmd" in $$source)) {
            this["suggestedCmd"] = "";
        }
        if (!("privilegeStrategy" in $$source)) {
            this["privilegeStrategy"] = "";
        }
        if (!("privilegeAttempted" in $$source)) {
            this["privilegeAttempted"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HookInstallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HookInstallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HookInstallResult($$parsedSource as Partial<HookInstallResult>);
    }
}

export class ValetLinuxRemediationResult {
    "generatedAt": string;
    "supported": boolean;
    "confirmed": boolean;
    "applied": boolean;
    "expectedPrependPath": string;
    "requiresSudo": boolean;
    "suggestedCommands": string[];
    "targets": ValetRemediationTarget[];
    "message": string;
    "error": string;

    /** Creates a new ValetLinuxRemediationResult instance. */
    constructor($$source: Partial<ValetLinuxRemediationResult> = {}) {
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("confirmed" in $$source)) {
            this["confirmed"] = false;
        }
        if (!("applied" in $$source)) {
            this["applied"] = false;
        }
        if (!("expectedPrependPath" in $$source)) {
            this["expectedPrependPath"] = "";
        }
        if (!("requiresSudo" in $$source)) {
            this["requiresSudo"] = false;
        }
        if (!("suggestedCommands" in $$source)) {
            this["suggestedCommands"] = [];
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetLinuxRemediationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ValetLinuxRemediationResult {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("suggestedCommands" in $$parsedSource) {
            $$parsedSource["suggestedCommands"] = $$createField6_0($$parsedSource["suggestedCommands"]);
        }
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField7_0($$parsedSource["targets"]);
        }
        return new ValetLinuxRemediationResult($$parsedSource as Partial<ValetLinuxRemediationResult>);
    }
}

export class ValetLinuxVerification {
    "generatedAt": string;
    "supported": boolean;
    "valetDetected": boolean;
    "serviceManager": string;
    "cliConfDPath": string;
    "cliAutoPrepend": string;
    "expectedPrependPath": string;
    "fpmServices": FPMServiceStatus[];
    "recommendations": string[];
    "lastError": string;

    /** Creates a new ValetLinuxVerification instance. */
    constructor($$source: Partial<ValetLinuxVerification> = {}) {
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("valetDetected" in $$source)) {
            this["valetDetected"] = false;
        }
        if (!("serviceManager" in $$source)) {
            this["serviceManager"] = "";
        }
        if (!("cliConfDPath" in $$source)) {
            this["cliConfDPath"] = "";
        }
        if (!("cliAutoPrepend" in $$source)) {
            this["cliAutoPrepend"] = "";
        }
        if (!("expectedPrependPath" in $$source)) {
            this["expectedPrependPath"] = "";
        }
        if (!("fpmServices" in $$source)) {
            this["fpmServices"] = [];
        }
        if (!("recommendations" in $$source)) {
            this["recommendations"] = [];
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetLinuxVerification instance from a string or object.
     */
    static createFrom($$source: any = {}): ValetLinuxVerification {
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fpmServices" in $$parsedSource) {
            $$parsedSource["fpmServices"] = $$createField7_0($$parsedSource["fpmServices"]);
        }
        if ("recommendations" in $$parsedSource) {
            $$parsedSource["recommendations"] = $$createField8_0($$parsedSource["recommendations"]);
        }
        return new ValetLinuxVerification($$parsedSource as Partial<ValetLinuxVerification>);
    }
}

export class ValetRemediationTarget {
    "serviceName": string;
    "hookIniPath": string;
    "writeAttempted": boolean;
    "written": boolean;
    "writeError": string;
    "restartAttempted": boolean;
    "restarted": boolean;
    "restartError": string;
    "restartCommand": string;

    /** Creates a new ValetRemediationTarget instance. */
    constructor($$source: Partial<ValetRemediationTarget> = {}) {
        if (!("serviceName" in $$source)) {
            this["serviceName"] = "";
        }
        if (!("hookIniPath" in $$source)) {
            this["hookIniPath"] = "";
        }
        if (!("writeAttempted" in $$source)) {
            this["writeAttempted"] = false;
        }
        if (!("written" in $$source)) {
            this["written"] = false;
        }
        if (!("writeError" in $$source)) {
            this["writeError"] = "";
        }
        if (!("restartAttempted" in $$source)) {
            this["restartAttempted"] = false;
        }
        if (!("restarted" in $$source)) {
            this["restarted"] = false;
        }
        if (!("restartError" in $$source)) {
            this["restartError"] = "";
        }
        if (!("restartCommand" in $$source)) {
            this["restartCommand"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetRemediationTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): ValetRemediationTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValetRemediationTarget($$parsedSource as Partial<ValetRemediationTarget>);
    }
}

export class ValetSite {
    "name": string;
    "path": string;
    "url": string;
    "isSecure": boolean;
    "phpVersion"?: string;

    /** Creates a new ValetSite instance. */
    constructor($$source: Partial<ValetSite> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("isSecure" in $$source)) {
            this["isSecure"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetSite instance from a string or object.
     */
    static createFrom($$source: any = {}): ValetSite {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValetSite($$parsedSource as Partial<ValetSite>);
    }
}

export class ValetSitesResult {
    "generatedAt": string;
    "supported": boolean;
    "os": string;
    "source": string;
    "sites": ValetSite[];
    "parkedDirectories": string[];
    "warnings": string[];
    "error": string;

    /** Creates a new ValetSitesResult instance. */
    constructor($$source: Partial<ValetSitesResult> = {}) {
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("sites" in $$source)) {
            this["sites"] = [];
        }
        if (!("parkedDirectories" in $$source)) {
            this["parkedDirectories"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValetSitesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ValetSitesResult {
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sites" in $$parsedSource) {
            $$parsedSource["sites"] = $$createField4_0($$parsedSource["sites"]);
        }
        if ("parkedDirectories" in $$parsedSource) {
            $$parsedSource["parkedDirectories"] = $$createField5_0($$parsedSource["parkedDirectories"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField6_0($$parsedSource["warnings"]);
        }
        return new ValetSitesResult($$parsedSource as Partial<ValetSitesResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ValetRemediationTarget.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FPMServiceStatus.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ValetSite.createFrom;
const $$createType6 = $Create.Array($$createType5);
