// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1: string): Promise<string>;
export function GetCollectorStatus(): Promise<{ running: boolean; socketPath: string; lastError: string; dropped: number }>;
export function GetRecentEvents(arg1: number): Promise<Array<{ id: string; timestamp: string; sourceType: string; projectRoot: string; isDd: boolean; payload: unknown }>>;
export function DumpEventChannelName(): Promise<string>;
export function GetSetupDiagnostics(): Promise<{ generatedAt: string; phpFound: boolean; phpVersion: string; phpIniOutput: string; serviceManager: string; lastError: string }>;
